package com.example.springjpa.src;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.springjpa.model.Users;
import com.example.springjpa.model.UsersContact;
import com.example.springjpa.model.UsersLog;
import com.example.springjpa.respository.UserRespository;
import com.example.springjpa.respository.UsersContactRepository;

@RequestMapping("/usercontact")
@RestController
public class UsersContactResource {
	@Autowired
	private UsersContactRepository usersContactRepository;
	
    @Autowired
	private UserRespository userRepo;
	
//	public UsersContactResource(UsersContactRepository usersContactRepository) {
//		this.usersContactRepository = usersContactRepository;
//	}
	
	
	@GetMapping(value = "/all")
	public List<UsersContact> getUsersContact() {
		return usersContactRepository.findAll();
	}
	
	// OnetoOne demonstration
	// even though usersContact have autogenerated Id but it only have id
	// until it call method save, this method return a usersContact object with id
	// and everything.
	@PostMapping(value="/update/{name}")
	public List<UsersContact> update(@PathVariable("name") String name) {
		UsersContact usersContact = new UsersContact();
					
		usersContact.setPhoneNo(111111);
		usersContact = usersContactRepository.save(usersContact);
		
		Users users = new Users(usersContact.getId(),name, 85000,"Development");
		usersContact.setUser(users);
		
		// create Logs
		UsersLog usersLog = new UsersLog();
		usersLog.setLog("HI youtuber");
		UsersLog usersLog2 = new UsersLog();
		usersLog2.setLog("Hello twice");
		
		users.setUsersLogs(Arrays.asList(usersLog, usersLog2));
		
		usersContactRepository.save(usersContact);
//		userRepo.save(users);
		
		
		return usersContactRepository.findAll();
	}
	
	@EntityGraph(attributePaths = "phoneNo")
	@GetMapping(value = "/usercontact/{id}")
	public Optional<UsersContact> getcontact(@PathVariable("id") Integer id) {
		return usersContactRepository.findById(id);
	}
}
